spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:h2:mem:filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
logging:
  level:
    ROOT: INFO
    org:
      zalando:
        logbook: TRACE